# Generated by Django 4.2 on 2023-05-14 09:16

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rdoc',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='profile',
            name='keywords_received',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdoc', models.FileField(upload_to=api.models.get_upload_path)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.profile')),
            ],
            options={
                'verbose_name_plural': 'Files',
            },
        ),
    ]
